openapi: 3.0.4
info:
  title: SpendCraft API
  version: 0.1.0

paths:
  /api/v1/register:
    post:
      summary: Registers a user
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                type: object
        
        "422":
          $ref: "#/components/responses/Error"

  /api/v1/groups:
    post:
      summary: Adds a group
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                required:
                  - data
                properties:
                  data:
                    $ref: "#/components/schemas/Group"
        "422":
          $ref: "#/components/responses/Error"
  
    get:
      summary: Gets the category tree
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                required:
                  - data
                properties:
                  data:
                    $ref: "#/components/schemas/CategoryTree"
        "422":
          $ref: "#/components/responses/Error"

  /api/v1/groups/{id}:
    patch:
      summary: Updates a group
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                required:
                  - data
                properties:
                  data:
                    $ref: "#/components/schemas/Group"

        "422":
          $ref: "#/components/responses/Error"

    delete:
      summary: Deletes a group
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                type: object
                
components:
  responses:
    Error:
      description: Error
      content:
        application/json:
          schema:
            type: object
            required:
              - errors
            properties:
              errors:
                type: array
                description: The errors
                items:
                  type: object
                  required:
                    - code
                    - detail
                    - source
                  properties:
                    code:
                      type: string
                    detail:
                      type: string
                    source:
                      type: object
                      required:
                        - pointer
                      properties:
                        pointer:
                          type: string

  schemas:
    Group:
      type: object
      required:
        - name
        - type
        - id
      description: The data
      properties:
        name:
          type: string
        type:
          type: string
          enum:
            - REGULAR
            - SYSTEM
            - NO GROUP
        id:
          type: number
        hidden:
          type: boolean
        parentGroupId:
          type: number
          nullable: true

    Category:
      type: object
      required:
        - id
        - groupId
        - name
        - balance
        - type
      properties:
        id:
          type: number
        groupId:
          type: number
        name:
          type: string
        balance:
          type: number
        type:
          type: string
          enum:
            - REGULAR
            - UNASSIGNED
            - FUNDING POOL
            - ACCOUNT TRANSFER
        hidden:
          type: boolean
        fundingAmount:
          type: number
        useGoal:
          type: boolean
        recurrence:
          type: number
        fundingCategories:
          type: array
          items:
            type: object
        goalDate:
          type: string
          nullable: true
          pattern: '^\d{3}-\d{2}-\d{4}$'
        includeFundingTransfers:
          type: boolean
        suspended:
          type: boolean

    CategoryTree:
      type: object
      required:
        - categories
        - groups
      properties:
        categories:
          type: array
          items:
            $ref: "#/components/schemas/Category"
        groups:
          type: array
          items: 
            $ref: "#/components/schemas/Group"
