openapi: 3.0.4
info:
  title: SpendCraft API
  version: 0.1.0

paths:
  /api/v1/register:
    post:
      summary: Registers a user
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                type: object
        
        "422":
          $ref: "#/components/responses/Error"

  /api/v1/groups:
    post:
      summary: Adds a group
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                required:
                  - data
                properties:
                  data:
                    $ref: "#/components/schemas/Group"
        "422":
          $ref: "#/components/responses/Error"
  
    get:
      summary: Gets the category tree
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                required:
                  - data
                properties:
                  data:
                    $ref: "#/components/schemas/CategoryTree"
        "422":
          $ref: "#/components/responses/Error"

  /api/v1/groups/{id}:
    patch:
      summary: Updates a group
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                required:
                  - data
                properties:
                  data:
                    $ref: "#/components/schemas/Group"

        "422":
          $ref: "#/components/responses/Error"

    delete:
      summary: Deletes a group
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      responses:
        "204":
          description: OK
          content:
            application/json:
              schema:
                type: object

        "409":
          $ref: "#/components/responses/Error"

                
  /api/v1/groups/{id}/categories:
    post:
      summary: Add category
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                required:
                  - data
                properties:
                  data:
                    $ref: "#/components/schemas/Category"

  /api/v1/groups/{groupId}/categories/{catId}:
    patch:
      summary: Update category
      parameters:
        - in: path
          name: groupId
          schema:
            type: integer
          required: true
        - in: path
          name: catId
          schema:
            type: integer
          required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                required:
                  - data
                properties:
                  data:
                    $ref: "#/components/schemas/Category"

    delete:
      summary: Delete category
      parameters:
        - in: path
          name: groupId
          schema:
            type: integer
          required: true
        - in: path
          name: catId
          schema:
            type: integer
          required: true
      responses:
        "204":
          description: OK
          content:
            application/json:
              schema:
                type: object

  /api/v1/institution:
    post:
      summary: 'Add institution'
      responses:
        "200":
          $ref: "#/components/responses/AddAccountsResponse"

  /api/v1/institution/{accountId}/accounts:
    post:
      summary: 'Add acccount to institution'
      parameters:
        - in: path
          name: accountId
          schema:
            type: integer
          required: true
      responses:
        "200":
          $ref: "#/components/responses/AddOfflineAccountsResponse"

  /api/v1/account/{accountId}/balances:
    post:
      summary: 'Add balance'
      parameters:
        - in: path
          name: accountId
          schema:
            type: integer
          required: true
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                type: object
                required:
                  - data
                properties:
                  data:
                    type: object
                    required:
                      - id
                      - balance
                      - date
                      - accountBalance
                    properties:
                      id:
                        type: integer
                      balance:
                        type: number
                      date:
                        type: string
                        format: date
                      accountBalance:
                        type: number

components:
  responses:
    Error:
      description: Error
      content:
        application/json:
          schema:
            type: object
            required:
              - errors
            properties:
              errors:
                type: array
                description: The errors
                items:
                  type: object
                  required:
                    - code
                    - detail
                  properties:
                    code:
                      type: string
                    detail:
                      type: string
                    source:
                      type: object
                      required:
                        - pointer
                      properties:
                        pointer:
                          type: string

    AddAccountsResponse:
      description: Add accounts response
      content:
        application/json:
          schema:
            type: object
            required:
              - data
            properties:
              data:
                type: object
                required:
                  - id
                  - plaidInstitutionId
                  - name
                  - syncDate
                  - accounts
                  - categories
                properties:
                  id:
                    type: integer
                  plaidInstitutionId:
                    type: string
                    nullable: true
                  name: 
                    type: string
                  syncDate:
                    type: string
                    nullable: true
                    format: date-time
                  Accounts:
                    type: array
                    items:
                      $ref: "#/components/schemas/Account"
                  categories:
                    type: array
                    items:
                      $ref: "#/components/schemas/CategoryBalance"

    AddOfflineAccountsResponse:
      description: Add accounts response
      content:
        application/json:
          schema:
            type: object
            required:
              - data
            properties:
              data:
                type: object
                required:
                  - account
                  - categories
                properties:
                  account:
                    $ref: "#/components/schemas/Account"
                  categories:
                    type: array
                    items:
                      $ref: "#/components/schemas/CategoryBalance"

  schemas:
    Group:
      type: object
      required:
        - name
        - type
        - id
      description: The data
      properties:
        name:
          type: string
        type:
          type: string
          enum:
            - REGULAR
            - SYSTEM
            - NO GROUP
        id:
          type: integer
        hidden:
          type: boolean
        parentGroupId:
          type: integer
          nullable: true

    Category:
      type: object
      required:
        - id
        - groupId
        - name
        - balance
        - type
      properties:
        id:
          type: integer
        groupId:
          type: integer
        name:
          type: string
        balance:
          type: number
        type:
          type: string
          enum:
            - REGULAR
            - UNASSIGNED
            - FUNDING POOL
            - ACCOUNT TRANSFER
        hidden:
          type: boolean
        fundingAmount:
          type: number
        useGoal:
          type: boolean
        recurrence:
          type: number
        fundingCategories:
          type: array
          items:
            type: object
        goalDate:
          type: string
          nullable: true
          format: date
        includeFundingTransfers:
          type: boolean
        suspended:
          type: boolean

    CategoryTree:
      type: object
      required:
        - categories
        - groups
      properties:
        categories:
          type: array
          items:
            $ref: "#/components/schemas/Category"
        groups:
          type: array
          items: 
            $ref: "#/components/schemas/Group"

    CategoryBalance:
      type: object
      required:
        - id
        - balance
      properties:
        id:
          type: integer
        balance:
          type: number

    Account:
      type: object
      required:
        - id
        - plaidId
        - name
        - type
        - subtype
        - closed
        - tracking
        - balance
      properties:
        id:
          type: integer
        plaidId:
          type: string
          nullable: true
        name:
          type: string
        type:
          type: string
          enum:
            - depository
            - credit
            - loan
            - investment
            - other
        subtype:
          type: string
        closed:
          type: boolean
        tracking:
          type: string
          enum:
            - None
            - Balances
            - Transactions
            - Uncategorized Transactions
        balance:
          type: number
        plaidBalance:
          type: number
        startDate:
          type: string
          format: date
        rate:
          type: number


