/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AccountTransactionSchema extends BaseModel {
  static $columns = ['accountId', 'accountOwner', 'amount', 'createdAt', 'id', 'location', 'merchantName', 'name', 'paymentChannel', 'pending', 'principle', 'provider', 'providerTransactionId', 'statementId', 'transactionId', 'updatedAt'] as const
  $columns = AccountTransactionSchema.$columns
  @column()
  declare accountId: number
  @column()
  declare accountOwner: string | null
  @column()
  declare amount: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare location: any | null
  @column()
  declare merchantName: string | null
  @column()
  declare name: string | null
  @column()
  declare paymentChannel: string | null
  @column()
  declare pending: boolean
  @column()
  declare principle: string | null
  @column()
  declare provider: string
  @column()
  declare providerTransactionId: string | null
  @column()
  declare statementId: number | null
  @column()
  declare transactionId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class AccountSchema extends BaseModel {
  static $columns = ['balance', 'closed', 'createdAt', 'enabled', 'id', 'initialized', 'institutionId', 'mask', 'name', 'officialName', 'plaidAccountId', 'plaidBalance', 'rate', 'startDate', 'subtype', 'syncDate', 'tracking', 'type', 'updatedAt'] as const
  $columns = AccountSchema.$columns
  @column()
  declare balance: string | null
  @column()
  declare closed: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare enabled: boolean | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare initialized: boolean
  @column()
  declare institutionId: number
  @column()
  declare mask: string | null
  @column()
  declare name: string | null
  @column()
  declare officialName: string | null
  @column()
  declare plaidAccountId: string | null
  @column()
  declare plaidBalance: string | null
  @column()
  declare rate: string | null
  @column.date()
  declare startDate: DateTime | null
  @column()
  declare subtype: string
  @column.dateTime()
  declare syncDate: DateTime | null
  @column()
  declare tracking: string | null
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ApnsTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'token', 'updatedAt', 'userId'] as const
  $columns = ApnsTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare token: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class ApplicationSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'updatedAt'] as const
  $columns = ApplicationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class AutoAssignmentCategorySchema extends BaseModel {
  static $columns = ['amount', 'autoAssignmentId', 'categoryId', 'createdAt', 'id', 'percentage', 'updatedAt'] as const
  $columns = AutoAssignmentCategorySchema.$columns
  @column()
  declare amount: number
  @column()
  declare autoAssignmentId: number
  @column()
  declare categoryId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare percentage: boolean | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class AutoAssignmentSchema extends BaseModel {
  static $columns = ['applicationId', 'createdAt', 'id', 'name', 'searchStrings', 'updatedAt'] as const
  $columns = AutoAssignmentSchema.$columns
  @column()
  declare applicationId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare searchStrings: any
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class BalanceHistorySchema extends BaseModel {
  static $columns = ['accountId', 'balance', 'createdAt', 'date', 'id', 'updatedAt'] as const
  $columns = BalanceHistorySchema.$columns
  @column()
  declare accountId: number
  @column()
  declare balance: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare date: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CategorySchema extends BaseModel {
  static $columns = ['balance', 'createdAt', 'fundingAmount', 'fundingCategories', 'goalDate', 'groupId', 'hidden', 'id', 'includeFundingTransfers', 'monthlyExpenses', 'name', 'recurrence', 'suspended', 'type', 'updatedAt', 'useGoal'] as const
  $columns = CategorySchema.$columns
  @column()
  declare balance: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare fundingAmount: string
  @column()
  declare fundingCategories: any
  @column.date()
  declare goalDate: DateTime | null
  @column()
  declare groupId: number
  @column()
  declare hidden: boolean
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare includeFundingTransfers: boolean
  @column()
  declare monthlyExpenses: boolean
  @column()
  declare name: string
  @column()
  declare recurrence: number
  @column()
  declare suspended: boolean
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare useGoal: boolean
}

export class FundingPlanCategorySchema extends BaseModel {
  static $columns = ['amount', 'categoryId', 'createdAt', 'expectedToSpend', 'goalDate', 'id', 'planId', 'recurrence', 'updatedAt', 'useGoal'] as const
  $columns = FundingPlanCategorySchema.$columns
  @column()
  declare amount: string
  @column()
  declare categoryId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare expectedToSpend: string | null
  @column.date()
  declare goalDate: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare planId: number
  @column()
  declare recurrence: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare useGoal: boolean
}

export class FundingPlanSchema extends BaseModel {
  static $columns = ['applicationId', 'createdAt', 'id', 'name', 'updatedAt'] as const
  $columns = FundingPlanSchema.$columns
  @column()
  declare applicationId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class GroupSchema extends BaseModel {
  static $columns = ['applicationId', 'createdAt', 'hidden', 'id', 'name', 'parentGroupId', 'system', 'type', 'updatedAt'] as const
  $columns = GroupSchema.$columns
  @column()
  declare applicationId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare hidden: boolean
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string | null
  @column()
  declare parentGroupId: number | null
  @column()
  declare system: boolean
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class InstitutionSchema extends BaseModel {
  static $columns = ['accessToken', 'applicationId', 'createdAt', 'cursor', 'id', 'institutionId', 'name', 'plaidItemId', 'syncDate', 'updatedAt'] as const
  $columns = InstitutionSchema.$columns
  @column()
  declare accessToken: string | null
  @column()
  declare applicationId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare cursor: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare institutionId: string | null
  @column()
  declare name: string | null
  @column()
  declare plaidItemId: string | null
  @column.dateTime()
  declare syncDate: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class LoanTransactionSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'loanId', 'principle', 'transactionCategoryId', 'updatedAt'] as const
  $columns = LoanTransactionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare loanId: number
  @column()
  declare principle: string
  @column()
  declare transactionCategoryId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class LoanSchema extends BaseModel {
  static $columns = ['balance', 'categoryId', 'createdAt', 'id', 'rate', 'startDate', 'startingBalance', 'updatedAt', 'userId'] as const
  $columns = LoanSchema.$columns
  @column()
  declare balance: string
  @column()
  declare categoryId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare rate: number
  @column.date()
  declare startDate: DateTime
  @column()
  declare startingBalance: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: number
}

export class PlaidLogSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'institutionId', 'request', 'response', 'status', 'updatedAt'] as const
  $columns = PlaidLogSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare institutionId: string | null
  @column()
  declare request: string | null
  @column()
  declare response: any | null
  @column()
  declare status: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PushSubscriptionSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'subscription', 'type', 'updatedAt', 'userId'] as const
  $columns = PushSubscriptionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare subscription: any
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class StatementSchema extends BaseModel {
  static $columns = ['accountId', 'createdAt', 'data', 'endDate', 'endingBalance', 'id', 'startDate', 'startingBalance', 'updatedAt'] as const
  $columns = StatementSchema.$columns
  @column()
  declare accountId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare data: any | null
  @column.date()
  declare endDate: DateTime
  @column()
  declare endingBalance: string
  @column({ isPrimary: true })
  declare id: number
  @column.date()
  declare startDate: DateTime
  @column()
  declare startingBalance: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TaxSchema extends BaseModel {
  static $columns = ['budgetId', 'createdAt', 'data', 'id', 'updatedAt', 'year'] as const
  $columns = TaxSchema.$columns
  @column()
  declare budgetId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare data: any
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare year: number
}

export class TestSchema extends BaseModel {
  static $columns = ['id', 'search', 'search2'] as const
  $columns = TestSchema.$columns
  @column()
  declare id: number | null
  @column()
  declare search: any | null
  @column()
  declare search2: any | null
}

export class TransactionCategorySchema extends BaseModel {
  static $columns = ['amount', 'categoryId', 'comment', 'createdAt', 'expected', 'id', 'transactionId', 'updatedAt'] as const
  $columns = TransactionCategorySchema.$columns
  @column()
  declare amount: string
  @column()
  declare categoryId: number
  @column()
  declare comment: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare expected: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare transactionId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class TransactionLogSchema extends BaseModel {
  static $columns = ['applicationId', 'changes', 'createdAt', 'id', 'message', 'transactionId', 'updatedAt'] as const
  $columns = TransactionLogSchema.$columns
  @column()
  declare applicationId: number
  @column()
  declare changes: any | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare message: string
  @column()
  declare transactionId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TransactionSchema extends BaseModel {
  static $columns = ['applicationId', 'categories', 'comment', 'createdAt', 'date', 'deleted', 'duplicateOfTransactionId', 'id', 'sortOrder', 'type', 'updatedAt', 'version'] as const
  $columns = TransactionSchema.$columns
  @column()
  declare applicationId: number
  @column()
  declare categories: any
  @column()
  declare comment: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare date: DateTime
  @column()
  declare deleted: boolean
  @column()
  declare duplicateOfTransactionId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare sortOrder: number | null
  @column()
  declare type: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare version: number | null
}

export class UserSchema extends BaseModel {
  static $columns = ['activated', 'applicationId', 'createdAt', 'email', 'id', 'oneTimePassCode', 'password', 'pendingEmail', 'rememberMeToken', 'roles', 'updatedAt', 'username'] as const
  $columns = UserSchema.$columns
  @column()
  declare activated: boolean
  @column()
  declare applicationId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare oneTimePassCode: any | null
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare pendingEmail: string | null
  @column()
  declare rememberMeToken: string | null
  @column()
  declare roles: any | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare username: string
}

export class WebhookLogSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'request', 'updatedAt'] as const
  $columns = WebhookLogSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare request: any | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
