export const REQUEST_PLANS = 'REQUEST_PLANS';
export const RECEIVE_PLANS = 'RECEIVE_PLANS';
export const REQUEST_PLAN = 'REQUEST_PLAN';
export const RECEIVE_PLAN = 'RECEIVE_PLAN';
export const UPDATE_PLAN_CATEGORY = 'UPDATE_PLAN_CATEGORY';
export const UPDATE_PLAN_ITEM = 'UPDATE_PLAN_ITEM';
