export const REQUEST_PLAN = 'REQUEST_PLAN';
export const RECEIVE_PLAN = 'RECEIVE_PLAN';
export const UPDATE_PLAN_CATEGORY = 'UPDATE_PLAN_CATEGORY';
export const UPDATE_PLAN_ITEM = 'UPDATE_PLAN_ITEM';
